In [1]:
import pandas as pd

In [2]:
appointments_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\appointments.csv")
billing_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\billing.csv")
doctors_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\doctors.csv")
patients_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\patients.csv")
treatments_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\treatments.csv")
hospital_catalog_df = pd.read_csv(r"C:\Users\vrehm\OneDrive\Desktop\Folders\personal\Hospital Mgt API\csv_files\hospital_dataset.csv")

In [12]:
display(appointments_df.columns)
display(billing_df.columns)
display(doctors_df.columns)
display(patients_df.columns)
display(treatments_df.columns)
display(hospital_catalog_df.columns)

Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_date',
       'appointment_time', 'reason_for_visit', 'status'],
      dtype='str')

Index(['bill_id', 'patient_id', 'treatment_id', 'bill_date', 'amount',
       'payment_method', 'payment_status'],
      dtype='str')

Index(['doctor_id', 'first_name', 'last_name', 'specialization',
       'phone_number', 'years_experience', 'hospital_branch', 'email'],
      dtype='str')

Index(['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth',
       'contact_number', 'address', 'registration_date', 'insurance_provider',
       'insurance_number', 'email'],
      dtype='str')

Index(['treatment_id', 'appointment_id', 'treatment_type', 'description',
       'cost', 'treatment_date'],
      dtype='str')

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [4]:
patients_df.tail()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
45,P046,Michael,Taylor,F,1986-09-01,8019925828,456 Oak Ave,2021-07-31,MedCare Plus,INS368799,michael.taylor@mail.com
46,P047,Jane,Moore,M,1995-12-13,8715732851,321 Maple Dr,2022-05-20,WellnessCorp,INS337549,jane.moore@mail.com
47,P048,Emily,Miller,M,1983-03-24,8720989381,123 Elm St,2023-06-19,PulseSecure,INS694319,emily.miller@mail.com
48,P049,David,Moore,M,1972-11-26,7712937941,321 Maple Dr,2023-06-14,MedCare Plus,INS584299,david.moore@mail.com
49,P050,Laura,Wilson,M,1993-12-27,8301134730,321 Maple Dr,2023-04-28,WellnessCorp,INS712210,laura.wilson@mail.com

In [5]:
doctors_df

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com
5,D006,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
6,D007,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
7,D008,Linda,Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com
8,D009,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
9,D010,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

In [6]:
doctors_df['specialization'].unique()
billing_df['payment_method'].unique()

<StringArray>
['Insurance', 'Credit Card', 'Cash']
Length: 3, dtype: str

In [7]:
billing_df.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [8]:
appointments_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [9]:
#check all chemotherapy desc and cost

In [10]:
treatments_df

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06
...,...,...,...,...,...,...
195,T196,A196,Chemotherapy,Advanced protocol,2477.80,2023-10-26
196,T197,A197,Physiotherapy,Standard procedure,975.49,2023-04-01
197,T198,A198,ECG,Basic screening,3383.72,2023-05-15
198,T199,A199,Chemotherapy,Basic screening,1472.17,2023-05-01
199,T200,A200,X-Ray,Basic screening,3288.15,2023-12-30

In [11]:
billing_df

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending
...,...,...,...,...,...,...,...
195,B196,P045,T196,2023-10-26,2477.80,Cash,Pending
196,B197,P001,T197,2023-04-01,975.49,Cash,Pending
197,B198,P022,T198,2023-05-15,3383.72,Cash,Failed
198,B199,P017,T199,2023-05-01,1472.17,Credit Card,Paid
199,B200,P007,T200,2023-12-30,3288.15,Insurance,Paid

In [13]:
hospital_catalog_df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [1]:
from huggingface_hub import InferenceClient

client = InferenceClient(
    model="mistralai/Mistral-7B-Instruct-v0.2",
    token="YOUR_TOKEN"
)

print(client.text_generation("Hello, how are you?", max_new_tokens=50))

ModuleNotFoundError: No module named 'huggingface_hub'

In [2]:
%pip install huggingface_hub

Collecting huggingface_hub
  Using cached huggingface_hub-1.16.1-py3-none-any.whl.metadata (14 kB)
Collecting filelock>=3.10.0 (from huggingface_hub)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub)
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface_hub)
  Using cached hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: packaging>=20.9 in C:\Users\vrehm\AppData\Roaming\Python\Python312\site-packages (from huggingface_hub) (26.2)
Collecting pyyaml>=5.1 (from huggingface_hub)
  Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting tqdm>=4.42.1 (from huggingface_hub)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting typer>=0.20.0 (from huggingface_hub)
  Using cached typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Collecting typing-extensions>=4.1.0 (from huggingface_hub)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface_hub)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface_hub)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface_hub)
  Downloading idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: colorama in C:\Users\vrehm\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Collecting click>=8.2.1 (from typer>=0.20.0->huggingface_hub)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer>=0.20.0->huggingface_hub)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer>=0.20.0->huggingface_hub)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.20.0->huggingface_hub)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer>=0.20.0->huggingface_hub)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\vrehm\AppData\Roaming\Python\Python312\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface_hub)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached huggingface_hub-1.16.1-py3-none-any.whl (668 kB)
Using cached hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached fsspec-2026.4.0-py3-none-any.whl (203 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Downloading idna-3.16-py3-none-any.whl (74 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Installing collected packages: typing-extensions, tqdm, shellingham, pyyaml, mdurl, idna, hf-xet, h11, fsspec, filelock, click, certifi, annotated-doc, markdown-it-py, httpcore, anyio, rich, httpx, typer, huggingface_hub

   ----------------------------------------  0/20 [typing-extensions]
   -- -------------------------------------  1/20 [tqdm]
   -- -------------------------------------  1/20 [tqdm]
   -- -------------------------------------  1/20 [tqdm]
   -- -------------------------------------  1/20 [tqdm]
   -- -------------------------------------  1/20 [tqdm]
   ---- -----------------------------------  2/20 [shellingham]
   ---- -----------------------------------  2/20 [shellingham]
   ------ ---------------------------------  3/20 [pyyaml]
   ------ ---------------------------------  3/20 [pyyaml]
   ---------- -----------------------------  5/20 [idna]
   ---------- -----------------------------  5/20 [idna]
   -------------- -------------------------  7/20 [h11]
   -------------- -------------------------  7/20 [h11]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ---------------- -----------------------  8/20 [fsspec]
   ------------------ ---------------------  9/20 [filelock]
   -------------------- ------------------- 10/20 [click]
   -------------------- ------------------- 10/20 [click]
   -------------------- ------------------- 10/20 [click]
   ---------------------- ----------------- 11/20 [certifi]
   -------------------------- ------------- 13/20 [markdown-it-py]
   -------------------------- ------------- 13/20 [markdown-it-py]
   -------------------------- ------------- 13/20 [markdown-it-py]
   -------------------------- ------------- 13/20 [markdown-it-py]
   -------------------------- ------------- 13/20 [markdown-it-py]
   ---------------------------- ----------- 14/20 [httpcore]
   ---------------------------- ----------- 14/20 [httpcore]
   ---------------------------- ----------- 14/20 [httpcore]
   ------------------------------ --------- 15/20 [anyio]
   ------------------------------ --------- 15/20 [anyio]
   ------------------------------ --------- 15/20 [anyio]
   ------------------------------ --------- 15/20 [anyio]
   ------------------------------ --------- 15/20 [anyio]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   -------------------------------- ------- 16/20 [rich]
   ---------------------------------- ----- 17/20 [httpx]
   ---------------------------------- ----- 17/20 [httpx]
   ---------------------------------- ----- 17/20 [httpx]
   ------------------------------------ --- 18/20 [typer]
   ------------------------------------ --- 18/20 [typer]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   -------------------------------------- - 19/20 [huggingface_hub]
   ---------------------------------------- 20/20 [huggingface_hub]

Successfully installed annotated-doc-0.0.4 anyio-4.13.0 certifi-2026.5.20 click-8.4.1 filelock-3.29.0 fsspec-2026.4.0 h11-0.16.0 hf-xet-1.5.0 httpcore-1.0.9 httpx-0.28.1 huggingface_hub-1.16.1 idna-3.16 markdown-it-py-4.2.0 mdurl-0.1.2 pyyaml-6.0.3 rich-15.0.0 shellingham-1.5.4 tqdm-4.67.3 typer-0.25.1 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install torch
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

Collecting torch
  Using cached torch-2.12.0-cp312-cp312-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: filelock in c:\Users\vrehm\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\Users\vrehm\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (4.15.0)
Collecting setuptools<82 (from torch)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: fsspec>=0.8.5 in c:\Users\vrehm\AppData\Local\Programs\Python\Python312\Lib\site-packages (from torch) (2026.4.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Using cached torch-2.12.0-cp312-cp312-win_amd64.whl (123.0 MB)
Using cached setuptools-81.0.0-py3-none-any.whl (1.1 MB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Installing collected packages: mpmath, sympy, setuptools, networkx, MarkupSafe, jinja2, torch

   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ---------------------------------------- 0/7 [mpmath]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----- ---------------------------------- 1/7 [sympy]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------- ---------------------------- 2/7 [setuptools]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ----------------- ---------------------- 3/7 [networkx]
   ---------------------------- ----------- 5/7 [jinja2]
   ---------------------------- ----------- 5/7 [jinja2]
   ---------------------------- ----------- 5/7 [jinja2]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]
   ---------------------------------- ----- 6/7 [torch]

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

False

AssertionError: Torch not compiled with CUDA enabled